---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/stable/manifests/install.yaml
  - app-projects

patches:
  - path: ./config-maps/argocd-cmd-params-cm.yaml
  - path: ./config-maps/argocd-cm.yaml
  - path: ./config-maps/argocd-image-updater-config.yaml
  - path: ./config-maps/argocd-notifications-cm.yaml
