# https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-demo/values.yaml
---
components:
  load-generator:
    enabled: false
  kafka:
    enabled: false
  llm:
    enabled: false
  postgresql:
    enabled: false
  valkey-cart:
    enabled: false
  accounting:
    envOverrides:
      - name: KAFKA_ADDR
        value: otel-demo.redpanda.svc.cluster.local:9093
      - name: DB_CONNECTION_STRING
        valueFrom:
          secretKeyRef:
            name: otel-demo-db
            key: accounting-dsn
    initContainers: []
  checkout:
    envOverrides:
      - name: KAFKA_ADDR
        value: otel-demo.redpanda.svc.cluster.local:9093
    initContainers: []
  fraud-detection:
    envOverrides:
      - name: KAFKA_ADDR
        value: otel-demo.redpanda.svc.cluster.local:9093
    initContainers: []
  cart:
    envOverrides:
      - name: VALKEY_ADDR
        value: valkey-otel-demo.valkey-operator-system.svc.cluster.local:6379
    initContainers: []
  product-reviews:
    envOverrides:
      - name: DB_CONNECTION_STRING
        valueFrom:
          secretKeyRef:
            name: otel-demo-db
            key: reviews-dsn
  product-catalog:
    resources:
      limits:
        memory: 120Mi
      requests:
        memory: 120Mi
    envOverrides:
      - name: DB_CONNECTION_STRING
        valueFrom:
          secretKeyRef:
            name: otel-demo-db
            key: catalog-dsn

opentelemetry-collector:
  enabled: false
jaeger:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
opensearch:
  enabled: false
